### PR TITLE
Modify file manager get function

### PR DESCRIPTION
**Pull request by Chiiizzzy**
Signed-off-by: Kaiyuan Hu <kaiyuan.hu@zilliz.com>

### CODE REVIEW

**Comment by shiyu22** [comment]
@Chiiizzzy This PR can also fix #463, because used `git` in `subprocess` instead of `gitpython`.

And can you remove `gitpython` in [requirements.txt](https://github.com/towhee-io/towhee/blob/main/requirements.txt)?

**Comment by Chiiizzzy** [comment]
> @Chiiizzzy This PR can also fix #463, because used `git` in `subprocess` instead of `gitpython`.
> 
> And can you remove `gitpython` in [requirements.txt](https://github.com/towhee-io/towhee/blob/main/requirements.txt)?

Cool, will do

**Comment by Chiiizzzy** [comment]
截屏2022-01-21 18 26 45

**Pull request merged**
