### PR TITLE
Add basic files: setup.py, ut example, coverage config

### PR DESCRIPTION
**Pull request by junjiejiangjjj**
#8 
1. Add setup.py
2. UT demo
3. Coverage config

### CODE REVIEW

**Comment by GuoRentong** [comment]
We'd better make pr's title clear and add the proper tags @junjiejiangjjj

**Review by GuoRentong — CHANGES_REQUESTED** [review]
We'd better make PR's title clear and add the proper tags

**Review by GuoRentong — APPROVED** [review]

**Review by derekdqc — APPROVED** [review]

**Review by derekdqc — COMMENTED** [review]
/lgtm

**Review by derekdqc — COMMENTED** [review]
/approve /lgtm

**Pull request merged**
